name: Build
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Build-Upload-Release:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - name: Build All
        run: |
          python ${{ github.workspace }}/build.py -pi
          python ${{ github.workspace }}/build.py -pi -o
          # python ${{ github.workspace }}/build.py -n
          # python ${{ github.workspace }}/build.py -n -o

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-download
          path: |
            ${{ github.workspace }}/op*.zip
          if-no-files-found: error
          retention-days: 30

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/op*.zip

